apiVersion: v1
kind: PersistentVolume
metadata:
  name: iam-mssql-server-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mssql
