apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iam-mssql-server-data
  namespace: numeraid-data
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
